# Site settings
title: Instalytics
subtitle: "Journal of Donald Rauscher"
email: donald.rauscher@gmail.com
description: "Data scientist, consultant, and aspiring entrepreneur"
baseurl: "/blog"
url: "http://donaldrauscher.github.io/blog"
github_username: "donaldrauscher"
linkedin_username: "donaldrauscher"
delicious_username: "djr45"
permalink: none

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
