# Site settings
title: Instalytics
subtitle: "Journal of Donald Rauscher"
email: donald.rauscher@gmail.com
description: "I manage the D4T4 & Analytics group at AbilTo, a healthcare startup based in NYC.  I studed Operations Research & Industrial Engineering at Cornell and received my MBA from the University of Michigan."
baseurl: ""
url: "http://donaldrauscher.com"
github_username: "donaldrauscher"
linkedin_username: "donaldrauscher"
delicious_username: "djr45"
permalink: none

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Gems
# gems: [jekyll-paginate]

# Sass
sass:
    style: :compressed
