# Site settings
title: DonaldRauscher.com
subtitle: "A Blog About D4T4 & M47H"
email: donald.rauscher@gmail.com
description: "I manage the D4T4 & Analytics group at [AbleTo](https://www.ableto.com/), a healthcare startup based in NYC.  I studed Operations Research & Industrial Engineering at Cornell and received my MBA from the University of Michigan."
url: "http://donaldrauscher.com"
github_username: "donaldrauscher"
linkedin_username: "donaldrauscher"
permalink: none
google_analytics: 'UA-89570331-1'
resources: [katex, plotly, jquery]
#host: 0.0.0.0

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Highligher
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination
paginate: 3
paginate_window: 4

# Gems
gems: [jekyll-paginate]

# Sass
sass:
    style: :compressed
